### ISSUE TITLE
not working npm run dev?

### ISSUE THREAD

**Issue by nsrtky** [almajiro/larafilm#1]
its just compiling web-pack but not statring localhost working. there is no documentation how to start it?

**Comment by almajiro** [comment]
Sorry, this project did not work well.
This project is backend of larafilm.
You need a frontend to use this project.
The frontend project is [here](https://github.com/almajiro/larafilm-frontend).
We are currently developing the frontend. Therefore, the development of the backend is not progressing.

I'm sorry for my bad English.
