### ISSUE TITLE
Demo & Documentation

### ISSUE THREAD

**Issue by jhemmmm** [almajiro/larafilm#11]
Hello,

It would be cool if there's a demo & documentation of the project. I might be able to help related to it.

**Comment by almajiro** [comment]
We are upgrading the framework to version 6.x and planning docker-compose to ease development.

This project has no documentation yet. sorry.

**Comment by jhemmmm** [comment]
> We are upgrading the framework to version 6.x and planning docker-compose to ease development.
> 
> This project has no documentation yet. sorry.

Upgrade it to 7.x instead. :)

**Comment by almajiro** [comment]
that's sounds good. i will upgrade to laravel 7.x
