### ISSUE TITLE
Class 'App\Constants\Larafilm' not found

### ISSUE THREAD

**Issue by ssk199441** [almajiro/larafilm#7]
public function render($request, Exception $exception)
    {
        if ($this->isHttpException($exception)) {
            if($exception->getStatusCode() == 404) {
                return response()->json([
                    'status' => 'failed',
                    'error' => [
                        'Not allowed action'
                    ],
                    'version' => Larafilm::VERSION
                ]);
            }
        }
 
        return parent::render($request, $exception);
    }
}

**Comment by almajiro** [comment]
Now Fixed
